language: node_js
python: 
    - "3.6"
node_js:
    - node

dist: trusty
sudo: false

before_install:
    - pip install --user awscli

install:
    - npm install

script:
    - CI=true npm test
    - npm run build

after_success:
    - echo "Success"
    - ./ci/deploy.sh